// Source of truth for the Experience and Education sections.
export const EXPERIENCE_DATA = [
  { title: 'Senior Software Engineer', org: 'ProxyFoods', url: 'https://proxyfoods.ai', location: 'Remote · Greece', companyLocation: 'Washington DC, USA', date: 'Feb 2025 - Present', tech: ['React 19', 'TypeScript', 'FastAPI', 'Python', 'LangGraph', 'OpenAI', 'Langfuse', 'OpenFGA', 'SQLAlchemy', 'Azure SQL', 'Docker', 'Azure', 'OpenTelemetry'], highlights: ['Formulation engine for nutrition, cost, sensory profiling, and mass-balance validation.', 'Agentic recipe generation with LangGraph, RAG, and human-in-the-loop ingredient matching.', 'Cross-service authorization with OpenFGA and shared auth, tracing, logging, and exception libraries.'] },
  { title: 'ML Engineer & Software Developer', org: 'MyTripMyWay', location: 'Greece', date: 'Jun 2025 - Mar 2026', tech: ['Next.js', 'React', 'MobX', 'Tailwind CSS', 'Leaflet', 'FastAPI', 'SQLAlchemy', 'MariaDB', 'Docker', 'Google Maps', 'Stripe'], highlights: ['Persona-based recommendations with six interpretable travel personas and itinerary feasibility modeling.', 'Full-stack POI aggregation, booking and payment flows, and interactive map-based itineraries.'] },
  { title: 'Full Stack Software Engineer', org: 'Behavioral Signals', url: 'https://behavioralsignals.com', location: 'Remote · Greece', companyLocation: 'USA', date: 'Mar 2024 - Feb 2025', tech: ['ReactJS', 'FastAPI', 'Django', 'Docker', 'Ansible', 'Azure', 'AWS', 'PostgreSQL', 'Milvus', 'MLflow'], highlights: ['Delivered agent matching, analytics, monitoring, and scalability improvements for real-time routing.', 'Designed, built, and owned the audio deepfake detection application end-to-end.'] },
  { title: 'Machine Learning Engineer', org: 'NCSR Demokritos', url: 'https://www.demokritos.gr', location: 'Ayia Paraskevi, Greece', date: 'Dec 2022 - Feb 2024', tech: ['ReactJS', 'FastAPI', 'PyTorch', 'FAISS', 'PostgreSQL', 'Docker', 'Balena', 'AWS', 'MLflow'], highlights: ['Built music copyright monitoring and inference pipelines for IoT and Raspberry Pi fleets.', 'Migrated models to deep learning and FAISS vector search to improve detection latency and accuracy.'], project: 'Museek' },
  { title: 'Lead Software Engineer', org: 'Optechain', url: 'https://optechain.com', location: 'Argyroupoli, Greece', date: 'Oct 2020 - Feb 2024', tech: ['React', 'Angular', 'Node.js', 'C#', 'Azure', 'Docker', 'MSSQL', 'Balena', 'Mender'], highlights: ['Led frontend and backend development for digital signage and EV-charging stations.', 'Ran the Azure and Docker stack and managed device-fleet updates for safer rollouts.'] },
  { title: 'Machine Learning Engineer', org: 'NCSR Demokritos', url: 'https://www.demokritos.gr', location: 'Ayia Paraskevi, Greece', date: 'Dec 2019 - Jul 2022', tech: ['PyTorch', 'scikit-learn', 'Python', 'Computer Vision', 'Multimodal ML'], highlights: ['Built video summarization and multimodal analysis models for the Enorasi project.', 'Improved summarization through model architecture and feature-fusion experiments.', 'Extended benchmark labeling to reduce evaluation variance.'], project: 'Enorasi' },
];

export const EDUCATION_DATA = [
  { degree: 'PhD Candidate in Computer Science', school: 'University of Thessaly', location: 'Lamia, Greece', date: '2021 - Present', thesis: undefined as string | undefined },
  { degree: 'MSc in Data Science', school: 'University of Peloponnese', location: 'Lamia, Greece', date: '2019 - 2021', thesis: 'Multimodal summarization of user-generated videos from wearable cameras' },
  { degree: 'BSc in Computer Science', school: 'University of Thessaly', location: 'Lamia, Greece', date: '2013 - 2018', thesis: undefined as string | undefined },
];
